###
POST http://localhost:3000/url/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNjQ5MDY1MCwiZXhwIjoxNzE2NDkyNDUwfQ.0t81Rxi2sHUvff87w5Z-xy3FfoLRe6Qa2KAtmhTVdM4
Content-Type: application/json

{
    "url" : "https://www.geeksforgeeks.org/express-js-res-redirect-function/",
    "customBackHalf" : "00018354"
}
###

###
//refresh
Get http://localhost:3000/user/refresh
###