###
POST http://localhost:3000/url/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNjYxNzIwMCwiZXhwIjoxNzE2NjE5MDAwfQ.mSJTDdL11VAIdLQ0uSpfsluD_LUnH-vPyCbrTQoMmno
Content-Type: application/json

{
    "url" : "https://www.geeksforgeeks.org/express-js-res-redirect-function/",
    "customBackHalf" : "00018354"
}
###

###
//refresh
Get http://localhost:3000/user/refresh
###